=== abusetelegram/xixi-haha/parse/data-branch-template/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/abusetelegram/xixi-haha/blob/data/schema.json",
  "title": "xixi-haha canonical article",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "id",
    "title",
    "date",
    "author",
    "editor",
    "article",
    "text"
  ],
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[1-9][0-9]*$"
    },
    "title": {
      "type": "string"
    },
    "date": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "editor": {
      "type": "string"
    },
    "article": {
      "type": "string"
    },
    "text": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "content_type": {
      "const": "image"
    },
    "media": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type",
          "url",
          "alt"
        ],
        "properties": {
          "type": {
            "const": "image"
          },
          "url": {
            "type": "string",
            "pattern": "^https?://(?![^/\\s]*@)[^\\s?#]+\\.(?:[jJ][pP][eE]?[gG]|[pP][nN][gG]|[gG][iI][fF]|[wW][eE][bB][pP]|[bB][mM][pP])(?:[?#][^\\s]*)?$"
          },
          "alt": {
            "type": "string"
          }
        }
      }
    }
  },
  "oneOf": [
    {
      "not": {
        "anyOf": [
          {
            "required": [
              "content_type"
            ]
          },
          {
            "required": [
              "media"
            ]
          }
        ]
      }
    },
    {
      "required": [
        "content_type",
        "media"
      ],
      "properties": {
        "text": {
          "maxItems": 0
        }
      }
    }
  ]
}

=== abusetelegram/xixi-haha/articles/31845277.json
{
  "id": "31845277",
  "title": "习近平：推动更深层次改革实行更高水平开放 为构建新发展格局提供强大动力",
  "date": "2020-09-01 20:44:31",
  "author": "新华网",
  "editor": "吕腾龙",
  "article": "<div class=\"d2txt_con clearfix\">\n<p></p><p style=\"text-align: center;\">\n<strong>习近平主持召开中央全面深化改革委员会第十五次会议强调</strong></p>\n<p style=\"text-align: center;\">\n<strong>推动更深层次改革实行更高水平开放</strong></p>\n<p style=\"text-align: center;\">\n<strong>为构建新发展格局提供强大动力</strong></p>\n<p style=\"text-align: center;\">\n<strong>李克强王沪宁韩正出席</strong></p>\n<p style=\"text-indent: 2em;\">\n新华社北京9月1日电 中共中央总书记、国家主席、中央军委主席、中央全面深化改革委员会主任习近平9月1日下午主持召开中央全面深化改革委员会第十五次会议并发表重要讲话。他强调，加快形成以国内大循环为主体、国内国际双循环相互促进的新发展格局，是根据我国发展阶段、环境、条件变化作出的战略决策，是事关全局的系统性深层次变革。要继续用足用好改革这个关键一招，保持勇往直前、风雨无阻的战略定力，围绕坚持和完善中国特色社会主义制度、推进国家治理体系和治理能力现代化，推动更深层次改革，实行更高水平开放，为构建新发展格局提供强大动力。</p>\n<p style=\"text-indent: 2em;\">\n中共中央政治局常委、中央全面深化改革委员会副主任李克强、王沪宁、韩正出席会议。</p>\n<p style=\"text-indent: 2em;\">\n习近平在讲话中指出，构建新发展格局，我们是有显著制度优势和坚实改革基础的。党的十八大以来，我们围绕落实新发展理念、推动高质量发展、扩大对外开放推出一系列重大改革举措，形成了一系列理论成果、制度成果、实践成果。要运用好这些改革成果，在抓落地见实效上加大力度、加快进度、拓展深度，使各项改革朝着推动形成新发展格局聚焦发力。</p>\n<p style=\"text-indent: 2em;\">\n习近平强调，当前形势下，构建新发展格局面临不少新情况新问题，要善于运用改革思维和改革办法，统筹考虑短期应对和中长期发展，既要在战略上布好局，也要在关键处落好子。要加快推进有利于提高资源配置效率的改革，有利于提高发展质量和效益的改革，有利于调动各方面积极性的改革，聚焦重点问题，加强改革举措的系统集成、协同高效，打通淤点堵点，激发整体效应。要把构建新发展格局同实施国家区域协调发展战略、建设自由贸易试验区等衔接起来，在有条件的区域率先探索形成新发展格局，打造改革开放新高地。要加强改革前瞻性研究，把握矛盾运动规律，守正创新、开拓创新，更加积极有效应对不稳定不确定因素，增强斗争本领，拓展政策空间，提升制度张力。</p>\n<p style=\"text-indent: 2em;\">\n会议审议通过了《关于推进对外贸易创新发展的实施意见》、《关于新时代振兴中西部高等教育的若干意见》、《关于规范民办义务教育发展的实施意见》、《关于进一步规范医疗行为促进合理医疗检查的指导意见》、《关于进一步推进生活垃圾分类工作的若干意见》。会议还听取了党的十八届三中全会以来农村改革进展情况汇报。</p>\n<p style=\"text-indent: 2em;\">\n会议指出，当前，经济全球化遭遇逆流，单边主义、保护主义抬头，我们决不能被逆风和回头浪所阻，要站在历史正确的一边，坚定不移扩大对外开放，增强国内国际经济联动效应，统筹发展和安全，全面防范风险挑战。推进对外贸易创新发展，要落实新发展理念，紧紧围绕构建新发展格局，以供给侧结构性改革为主线，深化科技创新、制度创新、业态和模式创新，加快提升贸易质量，稳定产业链供应链，培育外贸新动能，深入推进贸易便利化，优化外贸发展环境。</p>\n<p style=\"text-indent: 2em;\">\n会议强调，振兴中西部高等教育，要坚持和加强党对高校的全面领导，坚持中国特色社会主义教育发展道路，全面贯彻党的教育方针，落实立德树人根本任务，推动实现内涵式发展，主动对接重大区域发展战略，扎根中国大地办大学，突出优势特色、汇聚办学资源、促进要素流动，有效激发中西部高等教育内生动力和发展活力，推动形成同中西部开发开放格局相匹配的高等教育体系。</p>\n<p style=\"text-indent: 2em;\">\n会议指出，规范民办义务教育发展，目的是全面贯彻党的教育方针，坚持党对义务教育的全面领导，坚持社会主义办学方向，坚持依法治教，落实政府责任，加强分类指导，强化民办义务教育规范管理，营造良好教育生态，促进学生全面发展、健康成长。各级党委和政府要坚持国家举办义务教育，确保义务教育公益属性，办好办强公办义务教育。</p>\n<p style=\"text-indent: 2em;\">\n会议强调，这次应对新冠肺炎疫情，我们按照集中患者、集中专家、集中资源、集中救治的原则，坚持科学防治、精准施策，不断完善诊疗方案，调整优化诊疗程序、治疗药物和重症病人抢救措施，完善医保异地即时结算制度，医疗卫生体系发挥了重要作用。广大医务人员坚守医德医风、严格执业规范，表现出高度的责任感和奉献精神。进一步规范医疗行为、促进合理医疗检查，要从规范医疗主体行为入手，加大对医疗机构和医务人员行为的监督管理，加强技术创新，促进资源共享，统筹推进医疗管理体制、运行机制、服务价格、绩效分配等综合性改革，扎实推进行业作风建设。</p>\n<p style=\"text-indent: 2em;\">\n会议指出，生活垃圾分类关系人民群众日常生活，对于推动生态文明建设、提升社会文明程度、创新基层社会治理都有着重要意义。要从落实城市主体责任、推动群众习惯养成、加快分类设施建设、完善配套支持政策等方面入手，加快构建以法治为基础、政府推动、全民参与、城乡统筹、因地制宜的垃圾分类长效机制，树立科学理念，分类指导，加强全链条管理。</p>\n<p style=\"text-indent: 2em;\">\n会议强调，党的十八届三中全会以来，我们全面部署、系统推进农业农村改革，一些长期制约农业农村发展的体制机制障碍逐步得到破解，基础性关键性制度更加完善，农业农村优先发展的制度框架和政策体系初步形成，进一步解放和发展了农村社会生产力，增强了农业农村发展活力，为打赢脱贫攻坚战提供了重要制度支撑。要坚决守住土地公有制性质不改变、耕地红线不突破、农民利益不受损这三条底线，继续抓好重点领域和关键环节改革，统筹谋划、把稳方向、全力攻坚。要把保障粮食安全放在突出位置，健全粮食安全制度体系，加快转变农业发展方式，在探索现代农业发展道路上创造更多经验。要完善农村产权制度和要素市场化配置，提高农村土地、资金、人才、技术等各类要素的配置效率，激发农村内在活力。要健全农业支持保护制度，提高政策的精准性、指向性和实效性，引导农业发展由增产导向转为提质导向。要大力实施乡村振兴战略，健全城乡融合发展体制机制和政策体系。要注意加强改革系统集成，推动各项制度相互衔接、形成合力。要实事求是、因地制宜，依法依规、稳妥慎重，把握好各项工作的时度效，扎扎实实为民办事、为民造福。</p>\n<p style=\"text-indent: 2em;\">\n会议指出，党的十八届三中全会提出，到2020年要在重要领域和关键环节改革上取得决定性成果。这些年，全面深化改革从夯基垒台、立柱架梁，到全面推进、积厚成势，再到系统集成、协同高效，一路蹄疾步稳、勇毅笃行，在新起点上实现了新突破。各地区各部门要强化责任担当，增强紧迫感、提振精气神，全力完成党中央部署的改革任务。要做好党的十八届三中全会以来改革任务落实情况的总结评估，把总结评估同谋划“十四五”时期改革思路结合起来，同汇聚深化改革的强大力量结合起来，全面展示改革取得的重大成就和宝贵经验，坚定各方面深化改革的决心和信心，为开启全面建设社会主义现代化国家新征程积势蓄力。</p>\n<p style=\"text-indent: 2em;\">\n中央全面深化改革委员会委员出席会议，中央和国家机关有关部门负责同志列席会议。</p>\n</div>",
  "text": [
    "习近平主持召开中央全面深化改革委员会第十五次会议强调",
    "推动更深层次改革实行更高水平开放",
    "为构建新发展格局提供强大动力",
    "李克强王沪宁韩正出席",
    "新华社北京9月1日电 中共中央总书记、国家主席、中央军委主席、中央全面深化改革委员会主任习近平9月1日下午主持召开中央全面深化改革委员会第十五次会议并发表重要讲话。他强调，加快形成以国内大循环为主体、国内国际双循环相互促进的新发展格局，是根据我国发展阶段、环境、条件变化作出的战略决策，是事关全局的系统性深层次变革。要继续用足用好改革这个关键一招，保持勇往直前、风雨无阻的战略定力，围绕坚持和完善中国特色社会主义制度、推进国家治理体系和治理能力现代化，推动更深层次改革，实行更高水平开放，为构建新发展格局提供强大动力。",
    "中共中央政治局常委、中央全面深化改革委员会副主任李克强、王沪宁、韩正出席会议。",
    "习近平在讲话中指出，构建新发展格局，我们是有显著制度优势和坚实改革基础的。党的十八大以来，我们围绕落实新发展理念、推动高质量发展、扩大对外开放推出一系列重大改革举措，形成了一系列理论成果、制度成果、实践成果。要运用好这些改革成果，在抓落地见实效上加大力度、加快进度、拓展深度，使各项改革朝着推动形成新发展格局聚焦发力。",
    "习近平强调，当前形势下，构建新发展格局面临不少新情况新问题，要善于运用改革思维和改革办法，统筹考虑短期应对和中长期发展，既要在战略上布好局，也要在关键处落好子。要加快推进有利于提高资源配置效率的改革，有利于提高发展质量和效益的改革，有利于调动各方面积极性的改革，聚焦重点问题，加强改革举措的系统集成、协同高效，打通淤点堵点，激发整体效应。要把构建新发展格局同实施国家区域协调发展战略、建设自由贸易试验区等衔接起来，在有条件的区域率先探索形成新发展格局，打造改革开放新高地。要加强改革前瞻性研究，把握矛盾运动规律，守正创新、开拓创新，更加积极有效应对不稳定不确定因素，增强斗争本领，拓展政策空间，提升制度张力。",
    "会议审议通过了《关于推进对外贸易创新发展的实施意见》、《关于新时代振兴中西部高等教育的若干意见》、《关于规范民办义务教育发展的实施意见》、《关于进一步规范医疗行为促进合理医疗检查的指导意见》、《关于进一步推进生活垃圾分类工作的若干意见》。会议还听取了党的十八届三中全会以来农村改革进展情况汇报。",
    "会议指出，当前，经济全球化遭遇逆流，单边主义、保护主义抬头，我们决不能被逆风和回头浪所阻，要站在历史正确的一边，坚定不移扩大对外开放，增强国内国际经济联动效应，统筹发展和安全，全面防范风险挑战。推进对外贸易创新发展，要落实新发展理念，紧紧围绕构建新发展格局，以供给侧结构性改革为主线，深化科技创新、制度创新、业态和模式创新，加快提升贸易质量，稳定产业链供应链，培育外贸新动能，深入推进贸易便利化，优化外贸发展环境。",
    "会议强调，振兴中西部高等教育，要坚持和加强党对高校的全面领导，坚持中国特色社会主义教育发展道路，全面贯彻党的教育方针，落实立德树人根本任务，推动实现内涵式发展，主动对接重大区域发展战略，扎根中国大地办大学，突出优势特色、汇聚办学资源、促进要素流动，有效激发中西部高等教育内生动力和发展活力，推动形成同中西部开发开放格局相匹配的高等教育体系。",
    "会议指出，规范民办义务教育发展，目的是全面贯彻党的教育方针，坚持党对义务教育的全面领导，坚持社会主义办学方向，坚持依法治教，落实政府责任，加强分类指导，强化民办义务教育规范管理，营造良好教育生态，促进学生全面发展、健康成长。各级党委和政府要坚持国家举办义务教育，确保义务教育公益属性，办好办强公办义务教育。",
    "会议强调，这次应对新冠肺炎疫情，我们按照集中患者、集中专家、集中资源、集中救治的原则，坚持科学防治、精准施策，不断完善诊疗方案，调整优化诊疗程序、治疗药物和重症病人抢救措施，完善医保异地即时结算制度，医疗卫生体系发挥了重要作用。广大医务人员坚守医德医风、严格执业规范，表现出高度的责任感和奉献精神。进一步规范医疗行为、促进合理医疗检查，要从规范医疗主体行为入手，加大对医疗机构和医务人员行为的监督管理，加强技术创新，促进资源共享，统筹推进医疗管理体制、运行机制、服务价格、绩效分配等综合性改革，扎实推进行业作风建设。",
    "会议指出，生活垃圾分类关系人民群众日常生活，对于推动生态文明建设、提升社会文明程度、创新基层社会治理都有着重要意义。要从落实城市主体责任、推动群众习惯养成、加快分类设施建设、完善配套支持政策等方面入手，加快构建以法治为基础、政府推动、全民参与、城乡统筹、因地制宜的垃圾分类长效机制，树立科学理念，分类指导，加强全链条管理。",
    "会议强调，党的十八届三中全会以来，我们全面部署、系统推进农业农村改革，一些长期制约农业农村发展的体制机制障碍逐步得到破解，基础性关键性制度更加完善，农业农村优先发展的制度框架和政策体系初步形成，进一步解放和发展了农村社会生产力，增强了农业农村发展活力，为打赢脱贫攻坚战提供了重要制度支撑。要坚决守住土地公有制性质不改变、耕地红线不突破、农民利益不受损这三条底线，继续抓好重点领域和关键环节改革，统筹谋划、把稳方向、全力攻坚。要把保障粮食安全放在突出位置，健全粮食安全制度体系，加快转变农业发展方式，在探索现代农业发展道路上创造更多经验。要完善农村产权制度和要素市场化配置，提高农村土地、资金、人才、技术等各类要素的配置效率，激发农村内在活力。要健全农业支持保护制度，提高政策的精准性、指向性和实效性，引导农业发展由增产导向转为提质导向。要大力实施乡村振兴战略，健全城乡融合发展体制机制和政策体系。要注意加强改革系统集成，推动各项制度相互衔接、形成合力。要实事求是、因地制宜，依法依规、稳妥慎重，把握好各项工作的时度效，扎扎实实为民办事、为民造福。",
    "会议指出，党的十八届三中全会提出，到2020年要在重要领域和关键环节改革上取得决定性成果。这些年，全面深化改革从夯基垒台、立柱架梁，到全面推进、积厚成势，再到系统集成、协同高效，一路蹄疾步稳、勇毅笃行，在新起点上实现了新突破。各地区各部门要强化责任担当，增强紧迫感、提振精气神，全力完成党中央部署的改革任务。要做好党的十八届三中全会以来改革任务落实情况的总结评估，把总结评估同谋划“十四五”时期改革思路结合起来，同汇聚深化改革的强大力量结合起来，全面展示改革取得的重大成就和宝贵经验，坚定各方面深化改革的决心和信心，为开启全面建设社会主义现代化国家新征程积势蓄力。",
    "中央全面深化改革委员会委员出席会议，中央和国家机关有关部门负责同志列席会议。"
  ]
}

=== abusetelegram/xixi-haha/articles/31380423.json
{
  "id": "31380423",
  "title": "习近平致电祝贺中国女排夺得2019年女排世界杯冠军",
  "date": "2019-09-29 19:42:23",
  "author": "新华社",
  "editor": "王珂园",
  "article": "<div class=\"d2txt_con clearfix\">\n<p></p><p style=\"text-indent: 2em;\">\n新华社日本大阪9月29日电 中国女排夺得2019年女排世界杯冠军，成功卫冕。中共中央总书记、国家主席、中央军委主席习近平致电，向中国女排全体队员、教练员表示热烈的祝贺和诚挚的问候。</p>\n<p style=\"text-indent: 2em;\">\n习近平指出，在2019年女排世界杯比赛中，你们以十一连胜的骄人成绩夺得了冠军，成功卫冕，为祖国和人民赢得了荣誉。你们在比赛中不畏强手、敢打敢拼，打出了风格、赛出了水平，充分展现了团结协作、顽强拼搏的女排精神。我向你们表示热烈的祝贺和诚挚的问候！</p>\n<p style=\"text-indent: 2em;\">\n习近平强调，今年是新中国成立70周年，新中国取得的举世瞩目的伟大成就是全党全国各族人民团结一心、艰苦奋斗干出来的。希望你们继续保持昂扬斗志，不骄不躁，再创佳绩。</p>\n<p style=\"text-indent: 2em;\">\n2019年女排世界杯9月14日至29日在日本举行，中国女排连克强手，取得十一连胜的骄人成绩，成功卫冕世界杯冠军。1981年，在第三届女排世界杯上，中国女排获得第一个世界冠军，之后创造了“五连冠”的辉煌成绩。38年来，中国女排在世界杯、世锦赛、奥运会三大赛事中屡创佳绩，形成了团结协作、顽强拼搏的女排精神。</p>\n</div>",
  "text": [
    "新华社日本大阪9月29日电 中国女排夺得2019年女排世界杯冠军，成功卫冕。中共中央总书记、国家主席、中央军委主席习近平致电，向中国女排全体队员、教练员表示热烈的祝贺和诚挚的问候。",
    "习近平指出，在2019年女排世界杯比赛中，你们以十一连胜的骄人成绩夺得了冠军，成功卫冕，为祖国和人民赢得了荣誉。你们在比赛中不畏强手、敢打敢拼，打出了风格、赛出了水平，充分展现了团结协作、顽强拼搏的女排精神。我向你们表示热烈的祝贺和诚挚的问候！",
    "习近平强调，今年是新中国成立70周年，新中国取得的举世瞩目的伟大成就是全党全国各族人民团结一心、艰苦奋斗干出来的。希望你们继续保持昂扬斗志，不骄不躁，再创佳绩。",
    "2019年女排世界杯9月14日至29日在日本举行，中国女排连克强手，取得十一连胜的骄人成绩，成功卫冕世界杯冠军。1981年，在第三届女排世界杯上，中国女排获得第一个世界冠军，之后创造了“五连冠”的辉煌成绩。38年来，中国女排在世界杯、世锦赛、奥运会三大赛事中屡创佳绩，形成了团结协作、顽强拼搏的女排精神。"
  ]
}

=== abusetelegram/xixi-haha/articles/32523702.json
{
  "id": "32523702",
  "title": "习近平就朝鲜国庆74周年向朝鲜最高领导人金正恩致贺电",
  "date": "2022-09-10 08:04:38",
  "author": "人民网－人民日报",
  "editor": "(责编：任一林                     )",
  "article": "<div class=\"d2txt_con clearfix\">\n<p><p style=\"text-indent: 2em;\">\n\t新华社北京9月9日电  9月9日，中共中央总书记、国家主席习近平就朝鲜国庆74周年向朝鲜劳动党总书记、国务委员长金正恩致贺电。</p>\n<p style=\"text-indent: 2em;\">\n\t习近平指出，74年来，朝鲜人民紧密团结在朝鲜劳动党周围，砥砺奋进，推动社会主义建设事业取得重要成就。近年来，在朝鲜劳动党八大确定的方针政策指引下，朝鲜人民在发展经济、改善民生方面不断取得新成果，并成功抗击新冠肺炎疫情。作为好同志、好邻居、好朋友，我们对此感到由衷高兴。相信在总书记同志和朝鲜劳动党领导下，兄弟的朝鲜人民一定能够推动朝鲜社会主义事业实现新发展、迈上新台阶。</p>\n<p style=\"text-indent: 2em;\">\n\t习近平指出，中朝两国山水相连，传统友谊历久弥坚。我同总书记同志就规划两党两国关系发展蓝图、充实中朝友谊时代内涵达成一系列重要共识。中朝友好更加深入人心，两国交流合作持续推进，双方在彼此重大关切问题上相互支持，彰显了中朝传统友谊的蓬勃生机。</p>\n<p style=\"text-indent: 2em;\">\n\t习近平强调，百年未有之大变局加速演进，世界进入新的动荡变革期。中方愿同朝方保持战略沟通，加强协调合作，共同维护好、巩固好、发展好中朝关系，更好造福两国和两国人民，为地区乃至世界和平稳定与发展繁荣作出贡献。</p>\n<p style=\"text-indent: 2em;\">\n<span id=\"paper_num\" style=\"text-indent: 2em; display: block;\">《 人民日报 》（ 2022年09月10日 01 版）</span></p>\n</p>\n</div>",
  "text": [
    "新华社北京9月9日电  9月9日，中共中央总书记、国家主席习近平就朝鲜国庆74周年向朝鲜劳动党总书记、国务委员长金正恩致贺电。",
    "习近平指出，74年来，朝鲜人民紧密团结在朝鲜劳动党周围，砥砺奋进，推动社会主义建设事业取得重要成就。近年来，在朝鲜劳动党八大确定的方针政策指引下，朝鲜人民在发展经济、改善民生方面不断取得新成果，并成功抗击新冠肺炎疫情。作为好同志、好邻居、好朋友，我们对此感到由衷高兴。相信在总书记同志和朝鲜劳动党领导下，兄弟的朝鲜人民一定能够推动朝鲜社会主义事业实现新发展、迈上新台阶。",
    "习近平指出，中朝两国山水相连，传统友谊历久弥坚。我同总书记同志就规划两党两国关系发展蓝图、充实中朝友谊时代内涵达成一系列重要共识。中朝友好更加深入人心，两国交流合作持续推进，双方在彼此重大关切问题上相互支持，彰显了中朝传统友谊的蓬勃生机。",
    "习近平强调，百年未有之大变局加速演进，世界进入新的动荡变革期。中方愿同朝方保持战略沟通，加强协调合作，共同维护好、巩固好、发展好中朝关系，更好造福两国和两国人民，为地区乃至世界和平稳定与发展繁荣作出贡献。",
    "《 人民日报 》（ 2022年09月10日 01 版）"
  ]
}

=== abusetelegram/xixi-haha/articles/27833402.json
{
  "id": "27833402",
  "title": "习近平就我国公民被恐怖组织杀害事件发表讲话",
  "date": "2015-11-19 11:17:07",
  "author": "新华社",
  "editor": "姜萍萍",
  "article": "<div class=\"d2txt_con clearfix\">\n<p></p><p style=\"text-indent: 2em;\">\n１１月１９日，正在菲律宾马尼拉出席亚太经合组织第二十三次领导人非正式会议的国家主席习近平就我国公民被恐怖组织杀害事件发表讲话。</p>\n<p style=\"text-indent: 2em;\">\n习近平表示，中国强烈谴责“伊斯兰国”极端组织残忍杀害中国公民这一暴行。我向遇害者家属表示深切慰问。恐怖主义是人类的公敌，中国坚决反对一切形式的恐怖主义，坚决打击任何挑战人类文明底线的暴恐犯罪活动。（新华社马尼拉１１月１９日电）</p>\n</div>",
  "text": [
    "１１月１９日，正在菲律宾马尼拉出席亚太经合组织第二十三次领导人非正式会议的国家主席习近平就我国公民被恐怖组织杀害事件发表讲话。",
    "习近平表示，中国强烈谴责“伊斯兰国”极端组织残忍杀害中国公民这一暴行。我向遇害者家属表示深切慰问。恐怖主义是人类的公敌，中国坚决反对一切形式的恐怖主义，坚决打击任何挑战人类文明底线的暴恐犯罪活动。（新华社马尼拉１１月１９日电）"
  ]
}

=== abusetelegram/xixi-haha/articles/40378896.json
{
  "id": "40378896",
  "title": "征求对经济工作的意见和建议  中共中央召开党外人士座谈会  习近平主持并发表重要讲话李强通报有关情况  王沪宁蔡奇丁薛祥出席",
  "date": "2024-12-10 08:39:39",
  "author": "人民网－人民日报",
  "editor": "(责编：任佳晖)",
  "article": "<div class=\"d2txt_con clearfix\">\n<p><p style=\"text-indent: 2em; text-align: justify;\">■ 明年是“十四五”规划收官之年，要以新时代中国特色社会主义思想为指导，全面贯彻落实中共二十大和二十届二中、三中全会精神，坚持稳中求进工作总基调，完整准确全面贯彻新发展理念，加快构建新发展格局，扎实推动高质量发展，进一步全面深化改革，扩大高水平对外开放，建设现代化产业体系，更好统筹发展和安全，实施更加积极有为的宏观政策，扩大国内需求，推动科技创新和产业创新融合发展，稳住楼市股市，防范化解重点领域风险和外部冲击，稳定预期、激发活力，推动经济持续回升向好，不断提高人民生活水平，保持社会和谐稳定，高质量完成“十四五”规划目标任务，为实现“十五五”良好开局打牢基础</p>\n<p style=\"text-indent: 2em; text-align: justify;\">■ 今年，面对更加错综复杂的国际国内环境，中共中央团结带领全党全国各族人民，顶住压力、克服困难，沉着应变、综合施策，我国经济运行总体平稳、稳中有进，经济社会发展主要目标任务将顺利完成，中国式现代化迈出新的坚实步伐</p>\n<p style=\"text-indent: 2em; text-align: justify;\">■ 做好明年经济工作，首先必须坚定必胜信心。我国经济基础稳、优势多、韧性强、潜能大，长期向好的支撑条件和基本趋势没有变。我们要保持战略定力，主动塑造于我有利的外部环境，坚定不移办好自己的事，把各方面积极因素转化为发展实绩</p>\n<p style=\"text-indent: 2em; text-align: justify;\">■ 做好明年经济工作，需要全党全社会共同努力、艰苦奋斗。当前，我国发展面临许多不确定性和挑战，必须高度重视，切实加以解决。困难挑战年年有，但我们从来都是在风雨洗礼中发展、在历经考验中壮大的。要做好充分的工作准备，通过不懈努力实现明年经济社会发展目标，开创事业发展新局面</p>\n<p style=\"text-indent: 2em; text-align: justify;\">新华社北京12月9日电 12月6日，中共中央在中南海召开党外人士座谈会，就今年经济形势和明年经济工作听取各民主党派中央、全国工商联负责人和无党派人士代表的意见和建议。中共中央总书记习近平主持座谈会并发表重要讲话强调，明年是“十四五”规划收官之年，要以新时代中国特色社会主义思想为指导，全面贯彻落实中共二十大和二十届二中、三中全会精神，坚持稳中求进工作总基调，完整准确全面贯彻新发展理念，加快构建新发展格局，扎实推动高质量发展，进一步全面深化改革，扩大高水平对外开放，建设现代化产业体系，更好统筹发展和安全，实施更加积极有为的宏观政策，扩大国内需求，推动科技创新和产业创新融合发展，稳住楼市股市，防范化解重点领域风险和外部冲击，稳定预期、激发活力，推动经济持续回升向好，不断提高人民生活水平，保持社会和谐稳定，高质量完成“十四五”规划目标任务，为实现“十五五”良好开局打牢基础。</p>\n<p style=\"text-indent: 2em; text-align: justify;\">中共中央政治局常委李强、王沪宁、蔡奇、丁薛祥出席座谈会。李强受中共中央委托通报了今年经济工作有关情况，介绍了关于明年经济工作的有关考虑。</p>\n<p style=\"text-indent: 2em; text-align: justify;\">座谈会上，民革中央主席郑建邦、民盟中央主席丁仲礼、民建中央主席郝明金、民进中央主席蔡达峰、农工党中央主席何维、致公党中央主席蒋作君、九三学社中央主席武维华、台盟中央主席苏辉、全国工商联主席高云龙、无党派人士代表包信和先后发言。他们完全赞同中共中央对当前经济形势的分析判断和明年经济工作的谋划考虑，并就加快发展新质生产力、适当加大宏观调控力度、提高财政资金效益、强化科技创新生态建设、打造能源消费新生态、推进国家实验室建设、促进新增技能人才就业、促进民营经济健康发展、深化两岸融合发展等提出意见和建议。</p>\n<p style=\"text-indent: 2em; text-align: justify;\">在认真听取大家发言后，习近平表示，大家充分肯定了今年经济工作取得的成绩，就明年经济工作提了很多好的意见建议。我们将认真研究吸纳。</p>\n<p style=\"text-indent: 2em; text-align: justify;\">习近平指出，今年，面对更加错综复杂的国际国内环境，中共中央团结带领全党全国各族人民，顶住压力、克服困难，沉着应变、综合施策，我国经济运行总体平稳、稳中有进，经济社会发展主要目标任务将顺利完成，中国式现代化迈出新的坚实步伐。</p>\n<p style=\"text-indent: 2em; text-align: justify;\">习近平强调，今年以来，各民主党派、工商联和无党派人士聚焦推进中国式现代化，积极开展“发展新质生产力”、“畅通国内大循环”重点考察调研，加强长江生态环境保护民主监督，向中共中央报送各类调研报告、意见建议，为中共中央科学决策、有效施策提供了重要参考。习近平代表中共中央向大家表示衷心感谢。</p>\n<p style=\"text-indent: 2em; text-align: justify;\">习近平指出，做好明年经济工作，首先必须坚定必胜信心。我国经济基础稳、优势多、韧性强、潜能大，长期向好的支撑条件和基本趋势没有变。我们要保持战略定力，主动塑造于我有利的外部环境，坚定不移办好自己的事，把各方面积极因素转化为发展实绩。</p>\n<p style=\"text-indent: 2em; text-align: justify;\">习近平强调，做好明年经济工作，需要全党全社会共同努力、艰苦奋斗。当前，我国发展面临许多不确定性和挑战，必须高度重视，切实加以解决。困难挑战年年有，但我们从来都是在风雨洗礼中发展、在历经考验中壮大的。要做好充分的工作准备，通过不懈努力实现明年经济社会发展目标，开创事业发展新局面。</p>\n<p style=\"text-indent: 2em; text-align: justify;\">习近平对各民主党派、全国工商联和无党派人士提出3点希望。一是提高政治站位，协助党和政府做好经济工作。增强大局意识、全局观念，自觉在党和国家工作全局中充分发挥参政党作用。发挥统一战线独特优势，协助党和政府宣传政策、稳定预期、化解矛盾，引导广大成员及所联系群众全面辩证看待经济形势、发展大势，唱响主旋律、传递正能量。二是发挥人才荟萃优势，积极为中共中央决策献计出力。深入研究涉及改革发展稳定的关键问题，提出具有前瞻性和可操作性的意见建议。把准民主监督性质定位，加强工作统筹协同，助推各项国家战略的实施。三是加强自身建设，进一步增强参政议政能力。加强领导班子和队伍建设，从严要求、从严约束、从严监督，发现腐败行为严惩不贷。加强理论武装和知识更新，强化实践锻炼，不断提高履职本领和参政议政水平。</p>\n<p style=\"text-indent: 2em; text-align: justify;\">石泰峰、刘国中、何立峰、张国清、吴政隆，中共中央、国务院有关部门负责人出席座谈会。</p>\n<p style=\"text-indent: 2em; text-align: justify;\">出席座谈会的党外人士还有邵鸿、何报翔、王光谦、秦博勇、朱永新、杨震和张恩迪、安立佳、田轩等。</p>\n<p style=\"text-indent: 2em; text-align: justify;\"><span id=\"paper_num\"> 《 人民日报 》（ 2024年12月10日 01 版）</span></p> </p>\n</div>",
  "text": [
    "■ 明年是“十四五”规划收官之年，要以新时代中国特色社会主义思想为指导，全面贯彻落实中共二十大和二十届二中、三中全会精神，坚持稳中求进工作总基调，完整准确全面贯彻新发展理念，加快构建新发展格局，扎实推动高质量发展，进一步全面深化改革，扩大高水平对外开放，建设现代化产业体系，更好统筹发展和安全，实施更加积极有为的宏观政策，扩大国内需求，推动科技创新和产业创新融合发展，稳住楼市股市，防范化解重点领域风险和外部冲击，稳定预期、激发活力，推动经济持续回升向好，不断提高人民生活水平，保持社会和谐稳定，高质量完成“十四五”规划目标任务，为实现“十五五”良好开局打牢基础",
    "■ 今年，面对更加错综复杂的国际国内环境，中共中央团结带领全党全国各族人民，顶住压力、克服困难，沉着应变、综合施策，我国经济运行总体平稳、稳中有进，经济社会发展主要目标任务将顺利完成，中国式现代化迈出新的坚实步伐",
    "■ 做好明年经济工作，首先必须坚定必胜信心。我国经济基础稳、优势多、韧性强、潜能大，长期向好的支撑条件和基本趋势没有变。我们要保持战略定力，主动塑造于我有利的外部环境，坚定不移办好自己的事，把各方面积极因素转化为发展实绩",
    "■ 做好明年经济工作，需要全党全社会共同努力、艰苦奋斗。当前，我国发展面临许多不确定性和挑战，必须高度重视，切实加以解决。困难挑战年年有，但我们从来都是在风雨洗礼中发展、在历经考验中壮大的。要做好充分的工作准备，通过不懈努力实现明年经济社会发展目标，开创事业发展新局面",
    "新华社北京12月9日电 12月6日，中共中央在中南海召开党外人士座谈会，就今年经济形势和明年经济工作听取各民主党派中央、全国工商联负责人和无党派人士代表的意见和建议。中共中央总书记习近平主持座谈会并发表重要讲话强调，明年是“十四五”规划收官之年，要以新时代中国特色社会主义思想为指导，全面贯彻落实中共二十大和二十届二中、三中全会精神，坚持稳中求进工作总基调，完整准确全面贯彻新发展理念，加快构建新发展格局，扎实推动高质量发展，进一步全面深化改革，扩大高水平对外开放，建设现代化产业体系，更好统筹发展和安全，实施更加积极有为的宏观政策，扩大国内需求，推动科技创新和产业创新融合发展，稳住楼市股市，防范化解重点领域风险和外部冲击，稳定预期、激发活力，推动经济持续回升向好，不断提高人民生活水平，保持社会和谐稳定，高质量完成“十四五”规划目标任务，为实现“十五五”良好开局打牢基础。",
    "中共中央政治局常委李强、王沪宁、蔡奇、丁薛祥出席座谈会。李强受中共中央委托通报了今年经济工作有关情况，介绍了关于明年经济工作的有关考虑。",
    "座谈会上，民革中央主席郑建邦、民盟中央主席丁仲礼、民建中央主席郝明金、民进中央主席蔡达峰、农工党中央主席何维、致公党中央主席蒋作君、九三学社中央主席武维华、台盟中央主席苏辉、全国工商联主席高云龙、无党派人士代表包信和先后发言。他们完全赞同中共中央对当前经济形势的分析判断和明年经济工作的谋划考虑，并就加快发展新质生产力、适当加大宏观调控力度、提高财政资金效益、强化科技创新生态建设、打造能源消费新生态、推进国家实验室建设、促进新增技能人才就业、促进民营经济健康发展、深化两岸融合发展等提出意见和建议。",
    "在认真听取大家发言后，习近平表示，大家充分肯定了今年经济工作取得的成绩，就明年经济工作提了很多好的意见建议。我们将认真研究吸纳。",
    "习近平指出，今年，面对更加错综复杂的国际国内环境，中共中央团结带领全党全国各族人民，顶住压力、克服困难，沉着应变、综合施策，我国经济运行总体平稳、稳中有进，经济社会发展主要目标任务将顺利完成，中国式现代化迈出新的坚实步伐。",
    "习近平强调，今年以来，各民主党派、工商联和无党派人士聚焦推进中国式现代化，积极开展“发展新质生产力”、“畅通国内大循环”重点考察调研，加强长江生态环境保护民主监督，向中共中央报送各类调研报告、意见建议，为中共中央科学决策、有效施策提供了重要参考。习近平代表中共中央向大家表示衷心感谢。",
    "习近平指出，做好明年经济工作，首先必须坚定必胜信心。我国经济基础稳、优势多、韧性强、潜能大，长期向好的支撑条件和基本趋势没有变。我们要保持战略定力，主动塑造于我有利的外部环境，坚定不移办好自己的事，把各方面积极因素转化为发展实绩。",
    "习近平强调，做好明年经济工作，需要全党全社会共同努力、艰苦奋斗。当前，我国发展面临许多不确定性和挑战，必须高度重视，切实加以解决。困难挑战年年有，但我们从来都是在风雨洗礼中发展、在历经考验中壮大的。要做好充分的工作准备，通过不懈努力实现明年经济社会发展目标，开创事业发展新局面。",
    "习近平对各民主党派、全国工商联和无党派人士提出3点希望。一是提高政治站位，协助党和政府做好经济工作。增强大局意识、全局观念，自觉在党和国家工作全局中充分发挥参政党作用。发挥统一战线独特优势，协助党和政府宣传政策、稳定预期、化解矛盾，引导广大成员及所联系群众全面辩证看待经济形势、发展大势，唱响主旋律、传递正能量。二是发挥人才荟萃优势，积极为中共中央决策献计出力。深入研究涉及改革发展稳定的关键问题，提出具有前瞻性和可操作性的意见建议。把准民主监督性质定位，加强工作统筹协同，助推各项国家战略的实施。三是加强自身建设，进一步增强参政议政能力。加强领导班子和队伍建设，从严要求、从严约束、从严监督，发现腐败行为严惩不贷。加强理论武装和知识更新，强化实践锻炼，不断提高履职本领和参政议政水平。",
    "石泰峰、刘国中、何立峰、张国清、吴政隆，中共中央、国务院有关部门负责人出席座谈会。",
    "出席座谈会的党外人士还有邵鸿、何报翔、王光谦、秦博勇、朱永新、杨震和张恩迪、安立佳、田轩等。",
    "《 人民日报 》（ 2024年12月10日 01 版）"
  ]
}

=== abusetelegram/xixi-haha/articles/24918351.json
{
  "id": "24918351",
  "title": "习近平同加蓬总统邦戈互致贺电庆祝两国建交40周年",
  "date": "2014-04-20 10:55:55",
  "author": "新华网",
  "editor": "权娟",
  "article": "<div class=\"d2txt_con clearfix\">\n<p></p><p style=\"text-indent: 2em;\">\n国家主席习近平２０日同加蓬总统邦戈互致贺电，庆祝中加建交４０周年。</p>\n<p style=\"text-indent: 2em;\">\n习近平在贺电中说，４０年前，中加两国老一辈领导人作出建立大使级外交关系的决定，推动中加友好事业进入新的发展阶段。４０年来，中加两国政府和人民相互尊重、相互支持、真诚合作，结下了深厚友谊。进入新世纪以来，中加关系更是取得飞速发展，两国人民从双方合作中获益良多。中加同为发展中国家，同为中非命运共同体的成员，同样在为国家和民族发展振兴而奋斗。新形势下，把中加关系发展好符合两国人民根本利益。我高度重视中加关系发展，中方愿同加方一道，巩固传统友谊，深化友好合作，使中加关系焕发出新的生机活力。</p>\n<p style=\"text-indent: 2em;\">\n邦戈在贺电中说，加中建交４０年来，两国友好合作始终健康稳定发展。中国积极参与加蓬国家发展建设，是加实施“新兴加蓬战略计划”的重要战略伙伴。借此机会，我谨代表加蓬政府和人民并以我个人名义，对中国在加完成的诸多建设项目表示由衷的满意。此外，两国在多边事务中进行了成功合作。双方在许多重大问题上观点相近，在国际机构中保持着坦诚友好的合作与交流。我愿与你共同努力，不断深化和扩大加中两国间富有成果的友好合作关系。</p>\n<p style=\"text-indent: 2em;\">\n外交部长王毅也就中加建交４０周年与加外长恩贡代互致贺电。（新华网北京４月２０日电）</p>\n</div>",
  "text": [
    "国家主席习近平２０日同加蓬总统邦戈互致贺电，庆祝中加建交４０周年。",
    "习近平在贺电中说，４０年前，中加两国老一辈领导人作出建立大使级外交关系的决定，推动中加友好事业进入新的发展阶段。４０年来，中加两国政府和人民相互尊重、相互支持、真诚合作，结下了深厚友谊。进入新世纪以来，中加关系更是取得飞速发展，两国人民从双方合作中获益良多。中加同为发展中国家，同为中非命运共同体的成员，同样在为国家和民族发展振兴而奋斗。新形势下，把中加关系发展好符合两国人民根本利益。我高度重视中加关系发展，中方愿同加方一道，巩固传统友谊，深化友好合作，使中加关系焕发出新的生机活力。",
    "邦戈在贺电中说，加中建交４０年来，两国友好合作始终健康稳定发展。中国积极参与加蓬国家发展建设，是加实施“新兴加蓬战略计划”的重要战略伙伴。借此机会，我谨代表加蓬政府和人民并以我个人名义，对中国在加完成的诸多建设项目表示由衷的满意。此外，两国在多边事务中进行了成功合作。双方在许多重大问题上观点相近，在国际机构中保持着坦诚友好的合作与交流。我愿与你共同努力，不断深化和扩大加中两国间富有成果的友好合作关系。",
    "外交部长王毅也就中加建交４０周年与加外长恩贡代互致贺电。（新华网北京４月２０日电）"
  ]
}

=== abusetelegram/xixi-haha/articles/24714017.json
{
  "id": "24714017",
  "title": "习近平会见荷兰国王威廉—亚历山大",
  "date": "2014-03-24 07:14:10",
  "author": "人民网－人民日报",
  "editor": "杨丽娜",
  "article": "<div class=\"d2txt_con clearfix\">\n<p></p><table class=\"pci_c\" width=\"100%\">\n<tbody>\n<tr>\n<td align=\"center\">\n<img src=\"http://paper.people.com.cn/rmrb/res/1/20140324/1395612843406_1.jpg\"/></td>\n</tr>\n<tr>\n<td>\n<p style=\"text-indent: 2em;\">\n3月22日，国家主席习近平在阿姆斯特丹会见荷兰国王威廉—亚历山大。当习近平和夫人彭丽媛抵达王宫时，威廉—亚历山大国王和马克西玛王后热情迎接。双方进行了亲切友好的交谈。<br/>\n　　新华社记者 鞠 鹏摄</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p style=\"text-indent: 2em;\">\n人民网荷兰阿姆斯特丹3月22日电 （记者杜尚泽、丁大伟）国家主席习近平22日在阿姆斯特丹会见荷兰国王威廉—亚历山大。当习近平和夫人彭丽媛抵达王宫时，威廉—亚历山大国王和马克西玛王后热情迎接。双方进行了亲切友好的交谈。</p>\n<p style=\"text-indent: 2em;\">\n威廉—亚历山大国王热烈欢迎习近平访问荷兰。他高度评价荷中关系发展，表示荷兰王室长期同中国保持友好交往，我的母亲贝娅特丽克丝任女王期间多次访华。荷兰愿意做中国的好伙伴，希望加强两国务实合作和人文交往，相信习近平主席这次历史性访问必将推动荷中关系进一步发展。</p>\n<p style=\"text-indent: 2em;\">\n习近平表示，荷兰是最早承认新中国的西方国家之一。中荷合作规模和水平都处于中欧合作前列。荷兰已经连续11年保持中国在欧盟第二大贸易伙伴地位。荷兰也是欧盟第三大对华直接投资来源国。中国是荷兰在欧盟外第一大贸易伙伴和第二大投资来源国。这是因为两国人民都具有勤劳美德、务实精神和创新思维。</p>\n<p style=\"text-indent: 2em;\">\n习近平表示，当前，中国正在全面深化改革、扩大对外开放，朝着实现“两个一百年”的奋斗目标迈进。这对荷兰、对世界都是重大利好。我们欢迎荷方积极参与到这一进程中来，分享中国发展机遇，促进共同繁荣进步。我们也愿意学习借鉴荷兰的先进技术和管理经验。我希望通过这次访问，同荷方领导人共同规划两国关系未来发展方向，推动中荷关系迈上新台阶，为中欧关系作出新贡献。</p>\n<p style=\"text-indent: 2em;\">\n习近平赞赏威廉—亚历山大国王长期致力于中荷友好，特别是以自己的水利专业知识积极推动两国水利合作，相信荷兰王室将继续为两国关系发展作出贡献。</p>\n<p style=\"text-indent: 2em;\">\n双方就金融服务、打击恐怖主义等问题交换了意见，一致认为中荷两国应该加强合作，共同应对全球性挑战。</p>\n<p style=\"text-indent: 2em;\">\n当晚，威廉—亚历山大国王在王宫为习近平举行盛大国宴。王宫内水晶灯辉煌，郁金香花绽放。威廉—亚历山大国王、马克西玛王后、贝娅特丽克丝前女王共同迎接习近平和夫人彭丽媛到来。两国元首同双方嘉宾握手，互致问候。</p>\n<p style=\"text-indent: 2em;\">\n宴会上，威廉—亚历山大国王发表热情洋溢的讲话，表示习近平主席到访令荷兰人民深感荣幸。中国是古老又充满活力的国家。中国人民勤劳、智慧，正在为实现中国梦而奋斗。中国的发展对世界和平与繁荣至关重要。荷兰珍视同中国的友谊，愿同中国在实现各自美好梦想进程中携手合作。</p>\n<p style=\"text-indent: 2em;\">\n习近平在致辞中说，一踏上荷兰土地，我们就感受到荷兰人民对中国人民的友好情谊。中国和荷兰虽然分处亚欧大陆两端，但两国交往源远流长，是东西方文明互学互鉴、共同繁荣的典范。进入21世纪，中国同荷兰和欧洲更加紧密联系在一起。荷兰是欧洲的门户，我选择从荷兰推开欧洲的大门。欧洲是多极化世界中的重要一极。中方始终从战略高度看待中欧关系，愿同欧方加强全方位合作。希望荷兰为促进中欧关系发展作出新的更大贡献。</p>\n<p style=\"text-indent: 2em;\">\n宴会自始至终充满热烈友好的气氛。</p>\n<p style=\"text-indent: 2em;\">\n王沪宁、栗战书、杨洁篪等参加宴会。</p>\n<p style=\"text-indent: 2em;\">\n<span id=\"paper_num\" style=\"text-indent: 2em; display: block;\">《 人民日报 》（ 2014年03月24日 01 版）</span></p>\n</div>",
  "text": [
    "3月22日，国家主席习近平在阿姆斯特丹会见荷兰国王威廉—亚历山大。当习近平和夫人彭丽媛抵达王宫时，威廉—亚历山大国王和马克西玛王后热情迎接。双方进行了亲切友好的交谈。",
    "新华社记者 鞠 鹏摄",
    "人民网荷兰阿姆斯特丹3月22日电 （记者杜尚泽、丁大伟）国家主席习近平22日在阿姆斯特丹会见荷兰国王威廉—亚历山大。当习近平和夫人彭丽媛抵达王宫时，威廉—亚历山大国王和马克西玛王后热情迎接。双方进行了亲切友好的交谈。",
    "威廉—亚历山大国王热烈欢迎习近平访问荷兰。他高度评价荷中关系发展，表示荷兰王室长期同中国保持友好交往，我的母亲贝娅特丽克丝任女王期间多次访华。荷兰愿意做中国的好伙伴，希望加强两国务实合作和人文交往，相信习近平主席这次历史性访问必将推动荷中关系进一步发展。",
    "习近平表示，荷兰是最早承认新中国的西方国家之一。中荷合作规模和水平都处于中欧合作前列。荷兰已经连续11年保持中国在欧盟第二大贸易伙伴地位。荷兰也是欧盟第三大对华直接投资来源国。中国是荷兰在欧盟外第一大贸易伙伴和第二大投资来源国。这是因为两国人民都具有勤劳美德、务实精神和创新思维。",
    "习近平表示，当前，中国正在全面深化改革、扩大对外开放，朝着实现“两个一百年”的奋斗目标迈进。这对荷兰、对世界都是重大利好。我们欢迎荷方积极参与到这一进程中来，分享中国发展机遇，促进共同繁荣进步。我们也愿意学习借鉴荷兰的先进技术和管理经验。我希望通过这次访问，同荷方领导人共同规划两国关系未来发展方向，推动中荷关系迈上新台阶，为中欧关系作出新贡献。",
    "习近平赞赏威廉—亚历山大国王长期致力于中荷友好，特别是以自己的水利专业知识积极推动两国水利合作，相信荷兰王室将继续为两国关系发展作出贡献。",
    "双方就金融服务、打击恐怖主义等问题交换了意见，一致认为中荷两国应该加强合作，共同应对全球性挑战。",
    "当晚，威廉—亚历山大国王在王宫为习近平举行盛大国宴。王宫内水晶灯辉煌，郁金香花绽放。威廉—亚历山大国王、马克西玛王后、贝娅特丽克丝前女王共同迎接习近平和夫人彭丽媛到来。两国元首同双方嘉宾握手，互致问候。",
    "宴会上，威廉—亚历山大国王发表热情洋溢的讲话，表示习近平主席到访令荷兰人民深感荣幸。中国是古老又充满活力的国家。中国人民勤劳、智慧，正在为实现中国梦而奋斗。中国的发展对世界和平与繁荣至关重要。荷兰珍视同中国的友谊，愿同中国在实现各自美好梦想进程中携手合作。",
    "习近平在致辞中说，一踏上荷兰土地，我们就感受到荷兰人民对中国人民的友好情谊。中国和荷兰虽然分处亚欧大陆两端，但两国交往源远流长，是东西方文明互学互鉴、共同繁荣的典范。进入21世纪，中国同荷兰和欧洲更加紧密联系在一起。荷兰是欧洲的门户，我选择从荷兰推开欧洲的大门。欧洲是多极化世界中的重要一极。中方始终从战略高度看待中欧关系，愿同欧方加强全方位合作。希望荷兰为促进中欧关系发展作出新的更大贡献。",
    "宴会自始至终充满热烈友好的气氛。",
    "王沪宁、栗战书、杨洁篪等参加宴会。",
    "《 人民日报 》（ 2014年03月24日 01 版）"
  ]
}
