=== abusetelegram/xixi-haha/parse/data-branch-template/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/abusetelegram/xixi-haha/blob/data/schema.json",
  "title": "xixi-haha canonical article",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "id",
    "title",
    "date",
    "author",
    "editor",
    "article",
    "text"
  ],
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[1-9][0-9]*$"
    },
    "title": {
      "type": "string"
    },
    "date": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "editor": {
      "type": "string"
    },
    "article": {
      "type": "string"
    },
    "text": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "content_type": {
      "const": "image"
    },
    "media": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type",
          "url",
          "alt"
        ],
        "properties": {
          "type": {
            "const": "image"
          },
          "url": {
            "type": "string",
            "pattern": "^https?://(?![^/\\s]*@)[^\\s?#]+\\.(?:[jJ][pP][eE]?[gG]|[pP][nN][gG]|[gG][iI][fF]|[wW][eE][bB][pP]|[bB][mM][pP])(?:[?#][^\\s]*)?$"
          },
          "alt": {
            "type": "string"
          }
        }
      }
    }
  },
  "oneOf": [
    {
      "not": {
        "anyOf": [
          {
            "required": [
              "content_type"
            ]
          },
          {
            "required": [
              "media"
            ]
          }
        ]
      }
    },
    {
      "required": [
        "content_type",
        "media"
      ],
      "properties": {
        "text": {
          "maxItems": 0
        }
      }
    }
  ]
}

=== abusetelegram/xixi-haha/articles/31488285.json
{
  "id": "31488285",
  "title": "习近平会见出席“2019从都国际论坛”外方嘉宾",
  "date": "2019-12-04 07:14:36",
  "author": "人民网－人民日报",
  "editor": "王珂园",
  "article": "<div class=\"d2txt_con clearfix\">\n<p></p><table class=\"pci_c\" width=\"100%\">\n<tbody>\n<tr>\n<td align=\"center\">\n<img src=\"http://paper.people.com.cn/rmrb/res/1/20191204/1575401470383_1.jpg\"/></td>\n</tr>\n<tr>\n<td>\n<p style=\"text-indent: 2em;\">\n12月3日，国家主席习近平在北京人民大会堂会见出席“2019从都国际论坛”外方嘉宾。这是会见前，习近平同外方嘉宾集体合影。<br/>\n　　新华社记者 黄敬文摄</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p style=\"text-indent: 2em;\">\n中国特色社会主义道路是中国能够不断发展稳定的最根本原因，得到了全中国人民的衷心拥护和支持。我们将坚定不移继续沿着我们选择的道路走下去。中国将继续坚持改革开放，如期实现“两个一百年”奋斗目标。我对中国的未来充满信心</p>\n<p style=\"text-indent: 2em;\">\n一方水土养一方人。中国历来主张各国人民有权选择符合自身国情的发展道路。世界上没有哪一个国家和民族能够通过亦步亦趋、走别人的道路来实现自己的发展振兴，也没有一条一成不变的道路可以引导所有国家和民族实现发展振兴</p>\n<p style=\"text-indent: 2em;\">\n当前全球治理面临着复杂形势，国际秩序处在关键十字路口，实质是多边主义和单边主义之间何去何从的问题。现行国际秩序并不完美，但不必推倒重来，也不需另起炉灶，而是应在悉心维护的基础上改革完善。各国应承担起各自使命责任，开展建设性对话，坚持求同存异，坚持多边主义，为实现构建人类命运共同体这一宏伟目标发挥正能量</p>\n<p style=\"text-indent: 2em;\">\n本报北京12月3日电 （记者赵成）国家主席习近平3日在人民大会堂会见出席“2019从都国际论坛”外方嘉宾。</p>\n<p style=\"text-indent: 2em;\">\n习近平介绍了中国治国安邦之路和对当前国际形势的看法。习近平指出，今年是中华人民共和国成立70周年，这种历史性年份总会给人们带来深层次思考。新中国成立70年来，取得了伟大的发展成就。行稳才能致远。中国特色社会主义道路是中国能够不断发展稳定的最根本原因，得到了全中国人民的衷心拥护和支持。我们将坚定不移继续沿着我们选择的道路走下去。中国将继续坚持改革开放，如期实现“两个一百年”奋斗目标。我对中国的未来充满信心。</p>\n<p style=\"text-indent: 2em;\">\n习近平指出，一方水土养一方人。中国历来主张各国人民有权选择符合自身国情的发展道路。世界上没有哪一个国家和民族能够通过亦步亦趋、走别人的道路来实现自己的发展振兴，也没有一条一成不变的道路可以引导所有国家和民族实现发展振兴。中国要以自己的实践证明，国强未必称霸。这首先是中国五千年历史文化传统决定的，中国人没有扩张侵略的基因，秉持的是天下大同、天下为公的理念，不赞同你输我赢、零和博弈的思维。同时，中国在国际关系中坚持平等互利，愿与各国一道，共同构建人类命运共同体。中国愿与各国加强全面、深入、立体的相互了解，进而开展互利合作，实现共同繁荣。</p>\n<p style=\"text-indent: 2em;\">\n习近平强调，当今世界正经历百年未有之大变局，中国同世界的关系也在发生历史性变化。作为拥有近14亿人口的大国，中国做好自己的事，就是对人类社会最大的贡献，同时我们也愿意承担相应的国际义务和责任。当前全球治理面临着复杂形势，国际秩序处在关键十字路口，实质是多边主义和单边主义之间何去何从的问题。现行国际秩序并不完美，但不必推倒重来，也不需另起炉灶，而是应在悉心维护的基础上改革完善。各国应承担起各自使命责任，开展建设性对话，坚持求同存异，坚持多边主义，为实现构建人类命运共同体这一宏伟目标发挥正能量。</p>\n<p style=\"text-indent: 2em;\">\n拉脱维亚前总统弗赖贝加、坦桑尼亚前总统姆卡帕、日本前首相鸠山由纪夫、波黑主席团前成员伊万尼奇、美国前总统老布什三子尼尔·布什、斯洛文尼亚前总统图尔克等外方嘉宾先后发言，热烈祝贺中华人民共和国成立70周年，表示钦佩中国发展取得的伟大成就，赞赏中国为维护世界和平、促进可持续发展作出的重要贡献，中国人民现在享有着前所未有的自由，相信中国作为有重要影响力的大国将继续发展繁荣，实现中华民族伟大复兴的中国梦。他们表示，中国坚持改革开放，将使世界各国特别是发展中国家受益。而当前个别国家主张本国优先，奉行单边主义，导致冲突摩擦增多。世界需要坚持多边主义，完善全球治理，构建更加公平、公正、多元化的国际秩序。习近平主席提出的构建人类命运共同体、共建“一带一路”等重要倡议，对于维护世界和平繁荣、促进世界多极化和实现可持续发展具有重大积极意义，期待中方继续为应对气候变化等全球性挑战发挥重要引领作用。各方愿同中方一道，坚持多边主义，共建“一带一路”，推动构建相互尊重、合作共赢的新型国际关系。</p>\n<p style=\"text-indent: 2em;\">\n会见前，习近平同外方嘉宾集体合影。</p>\n<p style=\"text-indent: 2em;\">\n杨洁篪、王毅等参加会见。</p>\n<p style=\"text-indent: 2em;\">\n<span id=\"paper_num\" style=\"text-indent: 2em; display: block;\">《 人民日报 》（ 2019年12月04日 01 版）</span></p>\n</div>",
  "text": [
    "12月3日，国家主席习近平在北京人民大会堂会见出席“2019从都国际论坛”外方嘉宾。这是会见前，习近平同外方嘉宾集体合影。",
    "新华社记者 黄敬文摄",
    "中国特色社会主义道路是中国能够不断发展稳定的最根本原因，得到了全中国人民的衷心拥护和支持。我们将坚定不移继续沿着我们选择的道路走下去。中国将继续坚持改革开放，如期实现“两个一百年”奋斗目标。我对中国的未来充满信心",
    "一方水土养一方人。中国历来主张各国人民有权选择符合自身国情的发展道路。世界上没有哪一个国家和民族能够通过亦步亦趋、走别人的道路来实现自己的发展振兴，也没有一条一成不变的道路可以引导所有国家和民族实现发展振兴",
    "当前全球治理面临着复杂形势，国际秩序处在关键十字路口，实质是多边主义和单边主义之间何去何从的问题。现行国际秩序并不完美，但不必推倒重来，也不需另起炉灶，而是应在悉心维护的基础上改革完善。各国应承担起各自使命责任，开展建设性对话，坚持求同存异，坚持多边主义，为实现构建人类命运共同体这一宏伟目标发挥正能量",
    "本报北京12月3日电 （记者赵成）国家主席习近平3日在人民大会堂会见出席“2019从都国际论坛”外方嘉宾。",
    "习近平介绍了中国治国安邦之路和对当前国际形势的看法。习近平指出，今年是中华人民共和国成立70周年，这种历史性年份总会给人们带来深层次思考。新中国成立70年来，取得了伟大的发展成就。行稳才能致远。中国特色社会主义道路是中国能够不断发展稳定的最根本原因，得到了全中国人民的衷心拥护和支持。我们将坚定不移继续沿着我们选择的道路走下去。中国将继续坚持改革开放，如期实现“两个一百年”奋斗目标。我对中国的未来充满信心。",
    "习近平指出，一方水土养一方人。中国历来主张各国人民有权选择符合自身国情的发展道路。世界上没有哪一个国家和民族能够通过亦步亦趋、走别人的道路来实现自己的发展振兴，也没有一条一成不变的道路可以引导所有国家和民族实现发展振兴。中国要以自己的实践证明，国强未必称霸。这首先是中国五千年历史文化传统决定的，中国人没有扩张侵略的基因，秉持的是天下大同、天下为公的理念，不赞同你输我赢、零和博弈的思维。同时，中国在国际关系中坚持平等互利，愿与各国一道，共同构建人类命运共同体。中国愿与各国加强全面、深入、立体的相互了解，进而开展互利合作，实现共同繁荣。",
    "习近平强调，当今世界正经历百年未有之大变局，中国同世界的关系也在发生历史性变化。作为拥有近14亿人口的大国，中国做好自己的事，就是对人类社会最大的贡献，同时我们也愿意承担相应的国际义务和责任。当前全球治理面临着复杂形势，国际秩序处在关键十字路口，实质是多边主义和单边主义之间何去何从的问题。现行国际秩序并不完美，但不必推倒重来，也不需另起炉灶，而是应在悉心维护的基础上改革完善。各国应承担起各自使命责任，开展建设性对话，坚持求同存异，坚持多边主义，为实现构建人类命运共同体这一宏伟目标发挥正能量。",
    "拉脱维亚前总统弗赖贝加、坦桑尼亚前总统姆卡帕、日本前首相鸠山由纪夫、波黑主席团前成员伊万尼奇、美国前总统老布什三子尼尔·布什、斯洛文尼亚前总统图尔克等外方嘉宾先后发言，热烈祝贺中华人民共和国成立70周年，表示钦佩中国发展取得的伟大成就，赞赏中国为维护世界和平、促进可持续发展作出的重要贡献，中国人民现在享有着前所未有的自由，相信中国作为有重要影响力的大国将继续发展繁荣，实现中华民族伟大复兴的中国梦。他们表示，中国坚持改革开放，将使世界各国特别是发展中国家受益。而当前个别国家主张本国优先，奉行单边主义，导致冲突摩擦增多。世界需要坚持多边主义，完善全球治理，构建更加公平、公正、多元化的国际秩序。习近平主席提出的构建人类命运共同体、共建“一带一路”等重要倡议，对于维护世界和平繁荣、促进世界多极化和实现可持续发展具有重大积极意义，期待中方继续为应对气候变化等全球性挑战发挥重要引领作用。各方愿同中方一道，坚持多边主义，共建“一带一路”，推动构建相互尊重、合作共赢的新型国际关系。",
    "会见前，习近平同外方嘉宾集体合影。",
    "杨洁篪、王毅等参加会见。",
    "《 人民日报 》（ 2019年12月04日 01 版）"
  ]
}

=== abusetelegram/xixi-haha/articles/32584628.json
{
  "id": "32584628",
  "title": "习近平会见阿曼内阁副首相法赫德亲王",
  "date": "2022-12-10 11:37:38",
  "author": "人民网－人民日报",
  "editor": "(责编：王潇潇                     )",
  "article": "<div class=\"d2txt_con clearfix\">\n<p><table class=\"pci_c\" width=\"100%\">\n<tbody>\n<tr>\n<td align=\"center\">\n<img src=\"https://paper.people.com.cn/rmrb/images/1/20221210/1670636357703_1.jpg\"/></td>\n</tr>\n<tr>\n<td>\n<p>\n\t\t\t\t\t　　当地时间12月9日下午，国家主席习近平在利雅得会见阿曼内阁副首相法赫德亲王。<br/>\n\t\t\t\t\t　　新华社记者 黄敬文摄</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>\n\t　　本报利雅得12月9日电  （记者黄培昭、颜欢）当地时间12月9日下午，国家主席习近平在利雅得会见阿曼内阁副首相法赫德亲王。</p>\n<p>\n\t　　习近平指出，中阿友谊历史悠久，当年的海上丝绸之路把两国联系在一起。新形势下，中方愿同阿方巩固互信，深化友好合作，推动中阿战略伙伴关系取得新进展。希望阿曼继续积极参与中阿集体合作。祝贺阿曼即将担任下届海合会轮值主席国，愿同阿曼一道，推动中阿和中海关系取得新进展。</p>\n<p>\n\t　　法赫德表示，阿曼同中国的友谊源远流长。中国人民是友爱、善良的人民，中国是热爱和平、维护和平的国家。阿方期待进一步加强阿中关系。今天召开的首届海中、阿中峰会具有重要历史意义，阿方愿同中方一道，促进海中、阿中关系得到更大发展。</p>\n<p>\n\t　　丁薛祥、王毅、何立峰等参加会见。</p>\n<br/>\n<p>\n<span id=\"paper_num\">　　《 人民日报 》（ 2022年12月10日 03 版）</span></p>\n</p>\n</div>",
  "text": [
    "当地时间12月9日下午，国家主席习近平在利雅得会见阿曼内阁副首相法赫德亲王。",
    "新华社记者 黄敬文摄",
    "本报利雅得12月9日电  （记者黄培昭、颜欢）当地时间12月9日下午，国家主席习近平在利雅得会见阿曼内阁副首相法赫德亲王。",
    "习近平指出，中阿友谊历史悠久，当年的海上丝绸之路把两国联系在一起。新形势下，中方愿同阿方巩固互信，深化友好合作，推动中阿战略伙伴关系取得新进展。希望阿曼继续积极参与中阿集体合作。祝贺阿曼即将担任下届海合会轮值主席国，愿同阿曼一道，推动中阿和中海关系取得新进展。",
    "法赫德表示，阿曼同中国的友谊源远流长。中国人民是友爱、善良的人民，中国是热爱和平、维护和平的国家。阿方期待进一步加强阿中关系。今天召开的首届海中、阿中峰会具有重要历史意义，阿方愿同中方一道，促进海中、阿中关系得到更大发展。",
    "丁薛祥、王毅、何立峰等参加会见。",
    "《 人民日报 》（ 2022年12月10日 03 版）"
  ]
}

=== abusetelegram/xixi-haha/articles/27502337.json
{
  "id": "27502337",
  "title": "习近平会见国际田联主席迪亚克并接受国际田联金质荣誉勋章",
  "date": "2015-08-23 08:08:23",
  "author": "人民网－人民日报",
  "editor": "乔业琼",
  "article": "<div class=\"d2txt_con clearfix\">\n<p></p><table class=\"pci_c\" width=\"100%\">\n<tbody>\n<tr>\n<td align=\"center\">\n<img src=\"http://paper.people.com.cn/rmrb/res/1/20150823/1440265605935_1.jpg\"/></td>\n</tr>\n<tr>\n<td>\n<p style=\"text-indent: 2em;\">\n8月22日，国家主席习近平在北京国家体育场会见国际田联主席迪亚克并接受国际田联金质荣誉勋章。<br/>\n　　新华社记者　兰红光摄</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p style=\"text-indent: 2em;\">\n人民网北京8月22日电 （记者赵明昊）国家主席习近平22日在国家体育场会见国际田联主席迪亚克并接受国际田联金质荣誉勋章。</p>\n<p style=\"text-indent: 2em;\">\n习近平指出，国际田联在世界范围内大力发展田径运动，为促进奥林匹克运动发展、增进各国各地区人民友谊发挥了十分重要的作用。中国高度重视发展体育事业，致力于提高全体人民身体素质和健康水平，把参加体育运动作为在民众中倡导和推广文明生活方式的重要途径，把体育锻炼作为促进青少年身心健康成长的重要方式。</p>\n<p style=\"text-indent: 2em;\">\n习近平指出，田径世锦赛是当今世界规模最大、水平最高的田径体育盛会。我们希望通过举办北京田径世锦赛，推动世界田径运动发展，弘扬“更快、更高、更强”的奥林匹克精神，开展中国同世界各国在体育以及各领域合作，表达中国人民同各国人民共享发展成果、共创美好未来的真诚愿望。</p>\n<p style=\"text-indent: 2em;\">\n迪亚克表示，中国是个体育大国，为国际体育事业的发展作出了积极贡献，特别是在促进体育事业发展过程中推动了田径运动的大发展。国际田联愿进一步加强同中方的交流与合作。</p>\n<p style=\"text-indent: 2em;\">\n随后，迪亚克向习近平授予国际田联金质荣誉勋章，表彰习近平对世界田径事业所作杰出贡献。习近平感谢国际田联多年来对中国田径运动发展的支持，表示中国政府将一如既往支持田径运动发展，努力为世界田径运动发展作出更大贡献。</p>\n<p style=\"text-indent: 2em;\">\n刘延东、郭金龙、杨洁篪等参加会见。</p>\n<p style=\"text-indent: 2em;\">\n<span id=\"paper_num\" style=\"text-indent: 2em; display: block;\">《 人民日报 》（ 2015年08月23日 01 版）</span></p>\n</div>",
  "text": [
    "8月22日，国家主席习近平在北京国家体育场会见国际田联主席迪亚克并接受国际田联金质荣誉勋章。",
    "新华社记者　兰红光摄",
    "人民网北京8月22日电 （记者赵明昊）国家主席习近平22日在国家体育场会见国际田联主席迪亚克并接受国际田联金质荣誉勋章。",
    "习近平指出，国际田联在世界范围内大力发展田径运动，为促进奥林匹克运动发展、增进各国各地区人民友谊发挥了十分重要的作用。中国高度重视发展体育事业，致力于提高全体人民身体素质和健康水平，把参加体育运动作为在民众中倡导和推广文明生活方式的重要途径，把体育锻炼作为促进青少年身心健康成长的重要方式。",
    "习近平指出，田径世锦赛是当今世界规模最大、水平最高的田径体育盛会。我们希望通过举办北京田径世锦赛，推动世界田径运动发展，弘扬“更快、更高、更强”的奥林匹克精神，开展中国同世界各国在体育以及各领域合作，表达中国人民同各国人民共享发展成果、共创美好未来的真诚愿望。",
    "迪亚克表示，中国是个体育大国，为国际体育事业的发展作出了积极贡献，特别是在促进体育事业发展过程中推动了田径运动的大发展。国际田联愿进一步加强同中方的交流与合作。",
    "随后，迪亚克向习近平授予国际田联金质荣誉勋章，表彰习近平对世界田径事业所作杰出贡献。习近平感谢国际田联多年来对中国田径运动发展的支持，表示中国政府将一如既往支持田径运动发展，努力为世界田径运动发展作出更大贡献。",
    "刘延东、郭金龙、杨洁篪等参加会见。",
    "《 人民日报 》（ 2015年08月23日 01 版）"
  ]
}

=== abusetelegram/xixi-haha/articles/23446932.json
{
  "id": "23446932",
  "title": "组图：总书记来到湖南",
  "date": "2013-11-06 08:35:08",
  "author": "湖南日报",
  "editor": "杨丽娜",
  "article": "<div class=\"d2txt_con clearfix\">\n<p></p><p align=\"center\" style=\"text-align:center\">\n<img alt=\"\" src=\"http://www.people.com.cn/mediafile/pic/20131106/89/5315053693284331901.jpg\"/></p>\n<p>\n　　11月3日，习近平同志在湘西土家族苗族自治州花垣县排碧乡调研，与村民边走边谈。</p>\n<div style=\"page-break-after: always;\">\n<span style=\"display: none;\"> </span></div>\n<p align=\"center\" style=\"text-align:center\">\n<img alt=\"\" src=\"http://www.people.com.cn/mediafile/pic/20131106/83/4674271974740977275.jpg\"/></p>\n<p align=\"center\" class=\"pictext\" style=\"text-align:center\">\n　　11月3日，习近平同志来到位于吉首市的矮寨特大悬索桥视察。</p>\n<div style=\"page-break-after: always;\">\n<span style=\"display: none;\"> </span></div>\n<p align=\"center\" style=\"text-align:center\">\n<img alt=\"\" src=\"http://www.people.com.cn/mediafile/pic/20131106/90/18031603090370714278.jpg\"/></p>\n<p align=\"center\" class=\"pictext\" style=\"text-align:center\">\n　　11月3日，习近平同志在湘西土家族苗族自治州花垣县排碧乡同村民座谈。</p>\n<div style=\"page-break-after: always;\">\n<span style=\"display: none;\"> </span></div>\n<p align=\"center\" style=\"text-align:center\">\n<img alt=\"\" src=\"http://www.people.com.cn/mediafile/pic/20131106/24/17519455333167730080.jpg\"/></p>\n<p>\n　　11月3日下午，习近平同志在湘西土家族苗族自治州花垣县排碧乡十八洞村看望乡亲，调研扶贫开发工作。新华社记者 王晔 摄</p>\n<div style=\"page-break-after: always;\">\n<span style=\"display: none;\"> </span></div>\n<p align=\"center\" style=\"text-align:center\">\n<img alt=\"\" src=\"http://www.people.com.cn/mediafile/pic/20131106/58/1292198689907963050.jpg\"/></p>\n<p>\n　　11月3日，习近平同志在湘西土家族苗族自治州凤凰县廖家桥镇菖蒲塘村水果基地考察，与村民亲切交谈。</p>\n<div style=\"page-break-after: always;\">\n<span style=\"display: none;\"> </span></div>\n<p align=\"center\" style=\"text-align:center\">\n<img alt=\"\" src=\"http://www.people.com.cn/mediafile/pic/20131106/24/2676400199011874700.jpg\"/></p>\n<p>\n　　11月4日， 习近平同志来到中南大学，考察粉末冶金国家重点实验室，了解高校进行科技创新、服务国家重大战略项目情况。</p>\n<div style=\"page-break-after: always;\">\n<span style=\"display: none;\"> </span></div>\n<p align=\"center\" style=\"text-align:center\">\n<img alt=\"\" src=\"http://www.people.com.cn/mediafile/pic/20131106/26/3186577631676719242.jpg\"/></p>\n<p align=\"center\" class=\"pictext\" style=\"text-align:center\">\n　　11月4日，习近平同志在长沙考察威胜集团有限公司。（除署名外照片均由记者张目摄）</p>\n</div>",
  "text": [
    "11月3日，习近平同志在湘西土家族苗族自治州花垣县排碧乡调研，与村民边走边谈。",
    "11月3日，习近平同志来到位于吉首市的矮寨特大悬索桥视察。",
    "11月3日，习近平同志在湘西土家族苗族自治州花垣县排碧乡同村民座谈。",
    "11月3日下午，习近平同志在湘西土家族苗族自治州花垣县排碧乡十八洞村看望乡亲，调研扶贫开发工作。新华社记者 王晔 摄",
    "11月3日，习近平同志在湘西土家族苗族自治州凤凰县廖家桥镇菖蒲塘村水果基地考察，与村民亲切交谈。",
    "11月4日， 习近平同志来到中南大学，考察粉末冶金国家重点实验室，了解高校进行科技创新、服务国家重大战略项目情况。",
    "11月4日，习近平同志在长沙考察威胜集团有限公司。（除署名外照片均由记者张目摄）"
  ]
}

=== abusetelegram/xixi-haha/articles/31763222.json
{
  "id": "31763222",
  "title": "图解：建党99周年 跟着总书记学党章",
  "date": "2020-06-29 11:16:05",
  "author": "人民网-中国共产党新闻网",
  "editor": "吕腾龙",
  "article": "<div class=\"d2txt_con clearfix\">\n<p></p><p style=\"text-align: center\">\n<img alt=\"\" src=\"http://cpc.people.com.cn/NMediaFile/2020/0629/MAIN202006291115228698195538661.jpg\"/></p>\n</div>",
  "text": []
}

=== abusetelegram/xixi-haha/articles/31153742.json
{
  "id": "31153742",
  "title": "习近平向“2019·中国西藏发展论坛”致贺信",
  "date": "2019-06-15 08:29:23",
  "author": "人民网－人民日报",
  "editor": "任佳晖",
  "article": "<div class=\"d2txt_con clearfix\">\n<p></p><p style=\"text-indent: 2em;\">\n新华社北京6月14日电  6月14日，“2019·中国西藏发展论坛”在西藏拉萨举行。国家主席习近平发来贺信，向论坛开幕表示祝贺。</p>\n<p style=\"text-indent: 2em;\">\n习近平指出，西藏地处青藏高原腹地，是中国的一个重要边疆民族地区，是重要的生态安全屏障、重要的中华民族特色文化保护地、重要的世界旅游目的地。</p>\n<p style=\"text-indent: 2em;\">\n习近平强调，2019年是新中国成立70周年，也是西藏民主改革60周年。在中国共产党领导下，短短几十年，西藏实现了历史上最广泛最深刻的社会变革，百万农奴翻身解放，成为国家和社会的主人。在中央政府和全国人民大力支持下，西藏人民团结奋斗，把贫穷落后的旧西藏建设成了经济文化繁荣、社会全面进步、生态环境良好、人民生活幸福的新西藏。希望西藏抓住发展机遇，建设美丽幸福西藏，繁荣优秀传统文化，保护高原生态环境，实施更加积极的开放政策，广泛开展对外交流合作，描绘新时代西藏发展新画卷。</p>\n<p style=\"text-indent: 2em;\">\n<span id=\"paper_num\" style=\"text-indent: 2em; display: block;\">《 人民日报 》（ 2019年06月15日 03 版）</span></p>\n</div>",
  "text": [
    "新华社北京6月14日电  6月14日，“2019·中国西藏发展论坛”在西藏拉萨举行。国家主席习近平发来贺信，向论坛开幕表示祝贺。",
    "习近平指出，西藏地处青藏高原腹地，是中国的一个重要边疆民族地区，是重要的生态安全屏障、重要的中华民族特色文化保护地、重要的世界旅游目的地。",
    "习近平强调，2019年是新中国成立70周年，也是西藏民主改革60周年。在中国共产党领导下，短短几十年，西藏实现了历史上最广泛最深刻的社会变革，百万农奴翻身解放，成为国家和社会的主人。在中央政府和全国人民大力支持下，西藏人民团结奋斗，把贫穷落后的旧西藏建设成了经济文化繁荣、社会全面进步、生态环境良好、人民生活幸福的新西藏。希望西藏抓住发展机遇，建设美丽幸福西藏，繁荣优秀传统文化，保护高原生态环境，实施更加积极的开放政策，广泛开展对外交流合作，描绘新时代西藏发展新画卷。",
    "《 人民日报 》（ 2019年06月15日 03 版）"
  ]
}

=== abusetelegram/xixi-haha/articles/30390200.json
{
  "id": "30390200",
  "title": "习近平同古巴国务委员会主席兼部长会议主席迪亚斯-卡内尔举行会谈",
  "date": "2018-11-08 20:47:18",
  "author": "新华社",
  "editor": "吕腾龙",
  "article": "<div class=\"d2txt_con clearfix\">\n<p></p><p style=\"text-indent: 2em;\">\n国家主席习近平8日在人民大会堂同古巴国务委员会主席兼部长会议主席迪亚斯-卡内尔举行会谈。</p>\n<p style=\"text-indent: 2em;\">\n习近平欢迎迪亚斯-卡内尔对中国进行首次国事访问，请迪亚斯-卡内尔转达对劳尔·卡斯特罗第一书记的诚挚问候。习近平指出，古巴是一个了不起的伟大国家，半个世纪以来不畏艰难险阻，坚持走自己的道路，赢得了世界人民的尊重。中古同为社会主义国家，是好朋友、好同志、好兄弟。这是有事实证明，并且经受住时间和国际风云变幻考验的。中国人民不会忘记，58年前，菲德尔·卡斯特罗同志领导的古巴在西半球率先同新中国建交，他领导的古巴党和人民坚定支持中国人民维护主权和建设国家的正义事业。我两次访问古巴，同菲德尔同志深谈的情景至今历历在目。中古双方要倍加珍惜两国老一辈领导人亲手缔结和共同培育的中古友谊，把它继承好、发展好，共同谱写中古友好合作新篇章。</p>\n<p style=\"text-indent: 2em;\">\n习近平强调，中方高度赞赏古巴党、政府、人民坚定不移致力于发展中古关系的决心。双方要登高望远，统筹谋划，合力推动中古关系持续深入发展。政治上进一步巩固互信、相互支持，经济上互利共赢、相互帮助，治国理政上加强交流、相互借鉴。双方要在涉及彼此核心利益和重大关切的问题上继续坚定相互支持，中方将坚定支持古巴捍卫国家主权，走符合本国国情的社会主义道路，相信古巴人民在劳尔同志、主席同志等古巴领导人坚强有力的领导下，一定会与时俱进、开拓进取、团结奋斗，不断取得新的更大成就。中方赞赏古方长期以来为推动中国同拉美和加勒比国家关系发展发挥了积极和重要作用，愿同古方在重大国际和地区问题上保持密切协调。中方欢迎古方参与共建“一带一路”，双方要规划好经贸、能源、农业、旅游、生物制药等重点合作领域和项目，稳步向前推进。主席同志刚刚在上海参观了首届中国国际进口博览会。中方欢迎古方利用好这一平台，扩大对华出口。中国同古巴开展合作，秉持正确的义利观，能支持的，我们一定会支持。我们要在推进社会主义建设、改革发展等方面相互学习借鉴。要加强人文领域交流，增进两国人民，特别是青年人之间相互了解和友谊，将其转化为深化中古关系的持久动力。</p>\n<p style=\"text-indent: 2em;\">\n迪亚斯-卡内尔首先转达了劳尔·卡斯特罗第一书记对习近平主席的诚挚问候和良好祝愿。迪亚斯-卡内尔表示，古巴是西半球第一个同新中国建交的国家，古方为此深感骄傲。古巴人民对中国人民始终怀有友好感情，感谢中国一直支持古巴的正义事业，对古巴提供了宝贵帮助。菲德尔·卡斯特罗主席去世时，习近平主席亲赴古巴驻华使馆吊唁，令古巴人民深受感动。古巴新一代领导人会矢志不移地不断巩固和加强两国同志加兄弟般的传统友谊。古中关系建立在相互尊重和互信互利的基础之上，经历了国际风云变幻的考验，也一定能经得起未来的任何挑战。古巴钦佩中国发展取得的巨大成就，古巴党高度赞同中共十九大提出的发展理念，愿学习借鉴，更好地推进国内经济社会模式更新和社会主义建设事业。古中双方要继续保持高层交往和政治对话，加强经贸、教育、文化等领域交流，密切在国际事务中的沟通协调。</p>\n<p style=\"text-indent: 2em;\">\n会谈后，两国元首还共同见证了有关双边合作文件的签署。</p>\n<p style=\"text-indent: 2em;\">\n会谈前，习近平在人民大会堂北大厅为迪亚斯-卡内尔举行欢迎仪式。彭丽媛、白玛赤林、王毅、夏宝龙、何立峰等参加。</p>\n<p style=\"text-indent: 2em;\">\n（新华社北京11月8日电 记者白洁）</p>\n</div>",
  "text": [
    "国家主席习近平8日在人民大会堂同古巴国务委员会主席兼部长会议主席迪亚斯-卡内尔举行会谈。",
    "习近平欢迎迪亚斯-卡内尔对中国进行首次国事访问，请迪亚斯-卡内尔转达对劳尔·卡斯特罗第一书记的诚挚问候。习近平指出，古巴是一个了不起的伟大国家，半个世纪以来不畏艰难险阻，坚持走自己的道路，赢得了世界人民的尊重。中古同为社会主义国家，是好朋友、好同志、好兄弟。这是有事实证明，并且经受住时间和国际风云变幻考验的。中国人民不会忘记，58年前，菲德尔·卡斯特罗同志领导的古巴在西半球率先同新中国建交，他领导的古巴党和人民坚定支持中国人民维护主权和建设国家的正义事业。我两次访问古巴，同菲德尔同志深谈的情景至今历历在目。中古双方要倍加珍惜两国老一辈领导人亲手缔结和共同培育的中古友谊，把它继承好、发展好，共同谱写中古友好合作新篇章。",
    "习近平强调，中方高度赞赏古巴党、政府、人民坚定不移致力于发展中古关系的决心。双方要登高望远，统筹谋划，合力推动中古关系持续深入发展。政治上进一步巩固互信、相互支持，经济上互利共赢、相互帮助，治国理政上加强交流、相互借鉴。双方要在涉及彼此核心利益和重大关切的问题上继续坚定相互支持，中方将坚定支持古巴捍卫国家主权，走符合本国国情的社会主义道路，相信古巴人民在劳尔同志、主席同志等古巴领导人坚强有力的领导下，一定会与时俱进、开拓进取、团结奋斗，不断取得新的更大成就。中方赞赏古方长期以来为推动中国同拉美和加勒比国家关系发展发挥了积极和重要作用，愿同古方在重大国际和地区问题上保持密切协调。中方欢迎古方参与共建“一带一路”，双方要规划好经贸、能源、农业、旅游、生物制药等重点合作领域和项目，稳步向前推进。主席同志刚刚在上海参观了首届中国国际进口博览会。中方欢迎古方利用好这一平台，扩大对华出口。中国同古巴开展合作，秉持正确的义利观，能支持的，我们一定会支持。我们要在推进社会主义建设、改革发展等方面相互学习借鉴。要加强人文领域交流，增进两国人民，特别是青年人之间相互了解和友谊，将其转化为深化中古关系的持久动力。",
    "迪亚斯-卡内尔首先转达了劳尔·卡斯特罗第一书记对习近平主席的诚挚问候和良好祝愿。迪亚斯-卡内尔表示，古巴是西半球第一个同新中国建交的国家，古方为此深感骄傲。古巴人民对中国人民始终怀有友好感情，感谢中国一直支持古巴的正义事业，对古巴提供了宝贵帮助。菲德尔·卡斯特罗主席去世时，习近平主席亲赴古巴驻华使馆吊唁，令古巴人民深受感动。古巴新一代领导人会矢志不移地不断巩固和加强两国同志加兄弟般的传统友谊。古中关系建立在相互尊重和互信互利的基础之上，经历了国际风云变幻的考验，也一定能经得起未来的任何挑战。古巴钦佩中国发展取得的巨大成就，古巴党高度赞同中共十九大提出的发展理念，愿学习借鉴，更好地推进国内经济社会模式更新和社会主义建设事业。古中双方要继续保持高层交往和政治对话，加强经贸、教育、文化等领域交流，密切在国际事务中的沟通协调。",
    "会谈后，两国元首还共同见证了有关双边合作文件的签署。",
    "会谈前，习近平在人民大会堂北大厅为迪亚斯-卡内尔举行欢迎仪式。彭丽媛、白玛赤林、王毅、夏宝龙、何立峰等参加。",
    "（新华社北京11月8日电 记者白洁）"
  ]
}

=== abusetelegram/xixi-haha/articles/40690634.json
{
  "id": "40690634",
  "title": "中共中央政治局召开会议 审议《中国共产党地方委员会工作条例》中共中央总书记习近平主持会议",
  "date": "2026-03-28 08:23:44",
  "author": "人民网－人民日报",
  "editor": "(责编：刘圆圆)",
  "article": "<div class=\"d2txt_con clearfix\">\n<p><p>　<strong>　■ 地方党委要坚决维护以习近平同志为核心的党中央权威和集中统一领导，把贯彻落实党中央决策部署作为重中之重，对党中央定下来的事扭住不放、狠抓落实，同时紧密结合本地区实际，增强工作主动性、创造性</strong></p>\n<p><strong>　　■ 地方党委在谋发展保安全上责无旁贷，要脚踏实地、真抓实干。要完整准确全面贯彻新发展理念，扎扎实实推动高质量发展，着力保障和改善民生，全力维护国家安全和社会大局稳定。要树立和践行正确政绩观，坚持为人民出政绩、以实干出政绩，努力创造经得起实践、人民、历史检验的实绩。要在地方党委领导班子中强化民主集中制教育，完善议事决策规则，细化负面清单，健全监督机制，明确监督重点事项、具体措施、责任追究等内容，确保民主集中制严格贯彻执行。地方党委领导班子成员要加强理论学习，提高专业素质，着力提高领导能力。要扛起管党治党政治责任，坚定不移推进全面从严治党，锲而不舍严格贯彻中央八项规定及其实施细则精神，深入整治形式主义为基层减负，依法依规用权，守好廉洁底线，推动形成风清气正的政治生态</strong></p>\n<p>　　</p>\n<p>　　新华社北京3月27日电  中共中央政治局3月27日召开会议，审议《中国共产党地方委员会工作条例》。中共中央总书记习近平主持会议。</p>\n<p>　　会议指出，地方党委要坚决维护以习近平同志为核心的党中央权威和集中统一领导，把贯彻落实党中央决策部署作为重中之重，对党中央定下来的事扭住不放、狠抓落实，同时紧密结合本地区实际，增强工作主动性、创造性。</p>\n<p>　　会议强调，地方党委在谋发展保安全上责无旁贷，要脚踏实地、真抓实干。要完整准确全面贯彻新发展理念，扎扎实实推动高质量发展，着力保障和改善民生，全力维护国家安全和社会大局稳定。要树立和践行正确政绩观，坚持为人民出政绩、以实干出政绩，努力创造经得起实践、人民、历史检验的实绩。要在地方党委领导班子中强化民主集中制教育，完善议事决策规则，细化负面清单，健全监督机制，明确监督重点事项、具体措施、责任追究等内容，确保民主集中制严格贯彻执行。地方党委领导班子成员要加强理论学习，提高专业素质，着力提高领导能力。要扛起管党治党政治责任，坚定不移推进全面从严治党，锲而不舍严格贯彻中央八项规定及其实施细则精神，深入整治形式主义为基层减负，依法依规用权，守好廉洁底线，推动形成风清气正的政治生态。</p>\n<p>　　会议还研究了其他事项。</p>\n<p></p>\n<p><span id=\"paper_num\">　　《 人民日报 》（ 2026年03月28日 01 版）</span></p> </p>\n</div>",
  "text": [
    "■ 地方党委要坚决维护以习近平同志为核心的党中央权威和集中统一领导，把贯彻落实党中央决策部署作为重中之重，对党中央定下来的事扭住不放、狠抓落实，同时紧密结合本地区实际，增强工作主动性、创造性",
    "■ 地方党委在谋发展保安全上责无旁贷，要脚踏实地、真抓实干。要完整准确全面贯彻新发展理念，扎扎实实推动高质量发展，着力保障和改善民生，全力维护国家安全和社会大局稳定。要树立和践行正确政绩观，坚持为人民出政绩、以实干出政绩，努力创造经得起实践、人民、历史检验的实绩。要在地方党委领导班子中强化民主集中制教育，完善议事决策规则，细化负面清单，健全监督机制，明确监督重点事项、具体措施、责任追究等内容，确保民主集中制严格贯彻执行。地方党委领导班子成员要加强理论学习，提高专业素质，着力提高领导能力。要扛起管党治党政治责任，坚定不移推进全面从严治党，锲而不舍严格贯彻中央八项规定及其实施细则精神，深入整治形式主义为基层减负，依法依规用权，守好廉洁底线，推动形成风清气正的政治生态",
    "新华社北京3月27日电  中共中央政治局3月27日召开会议，审议《中国共产党地方委员会工作条例》。中共中央总书记习近平主持会议。",
    "会议指出，地方党委要坚决维护以习近平同志为核心的党中央权威和集中统一领导，把贯彻落实党中央决策部署作为重中之重，对党中央定下来的事扭住不放、狠抓落实，同时紧密结合本地区实际，增强工作主动性、创造性。",
    "会议强调，地方党委在谋发展保安全上责无旁贷，要脚踏实地、真抓实干。要完整准确全面贯彻新发展理念，扎扎实实推动高质量发展，着力保障和改善民生，全力维护国家安全和社会大局稳定。要树立和践行正确政绩观，坚持为人民出政绩、以实干出政绩，努力创造经得起实践、人民、历史检验的实绩。要在地方党委领导班子中强化民主集中制教育，完善议事决策规则，细化负面清单，健全监督机制，明确监督重点事项、具体措施、责任追究等内容，确保民主集中制严格贯彻执行。地方党委领导班子成员要加强理论学习，提高专业素质，着力提高领导能力。要扛起管党治党政治责任，坚定不移推进全面从严治党，锲而不舍严格贯彻中央八项规定及其实施细则精神，深入整治形式主义为基层减负，依法依规用权，守好廉洁底线，推动形成风清气正的政治生态。",
    "会议还研究了其他事项。",
    "《 人民日报 》（ 2026年03月28日 01 版）"
  ]
}
